package com.neoutils.engine.bundle.python

import com.neoutils.engine.bundle.script.*
import com.neoutils.engine.input.Key
import com.neoutils.engine.math.Rect
import com.neoutils.engine.math.Transform
import com.neoutils.engine.math.Vec2
import com.neoutils.engine.physics.BoxCollider
import com.neoutils.engine.render.Color
import com.neoutils.engine.render.Renderer
import com.neoutils.engine.scene.Node
import com.neoutils.engine.scene.Node2D
import com.neoutils.engine.serialization.NodeRef
import com.neoutils.engine.serialization.NodeRegistry
import org.graalvm.polyglot.Context
import org.graalvm.polyglot.Source
import org.graalvm.polyglot.Value
import org.graalvm.polyglot.proxy.ProxyExecutable
import kotlin.reflect.KClass

class PythonScriptHost private constructor(private val context: Context) : ScriptHost {

    override val extension = ".py"

    private val moduleCache = mutableMapOf<String, Value>()

    private val loadModuleFn: Value
    private val inspectFn: Value
    private val parseExtendsFn: Value
    private val createInstanceFn: Value

    init {
        val bindings = context.getBindings("python")
        // Value-type ctors are exposed as ProxyExecutable factories so script
        // code calls `Vec2(1.0, 2.0)` against a Kotlin entry point that does
        // the `double → float` cast explicitly. Binding the raw Kotlin class
        // doesn't work for Color/Rect/Vec2 because Python floats are doubles
        // and GraalPy can't always pick the right (float, float, ...) ctor
        // among the synthetic ones generated by `@Serializable` and Kotlin
        // default args (symptom: "invalid instantiation of foreign object").
        bindings.putMember("Vec2", ProxyExecutable { args ->
            Vec2(args[0].asDouble().toFloat(), args[1].asDouble().toFloat())
        })
        bindings.putMember("Color", ProxyExecutable { args ->
            val r = args[0].asDouble().toFloat()
            val g = args[1].asDouble().toFloat()
            val b = args[2].asDouble().toFloat()
            val a = if (args.size >= 4) args[3].asDouble().toFloat() else 1f
            Color(r, g, b, a)
        })
        bindings.putMember("Rect", ProxyExecutable { args ->
            Rect(args[0].asHostObject(), args[1].asHostObject())
        })
        // Transform factory: 3-arg with explicit `double → float` rotation
        // cast, plus a 1-arg shortcut for position-only updates (the most
        // common mutation pattern in scripts, replacing Kotlin's `copy(...)`).
        bindings.putMember("Transform", ProxyExecutable { args ->
            when (args.size) {
                0 -> Transform()
                1 -> Transform(position = args[0].asHostObject())
                2 -> Transform(
                    position = args[0].asHostObject(),
                    scale = args[1].asHostObject(),
                )
                3 -> Transform(
                    position = args[0].asHostObject(),
                    scale = args[1].asHostObject(),
                    rotation = args[2].asDouble().toFloat(),
                )
                else -> error("Transform takes 0..3 args (position, scale, rotation)")
            }
        })
        // NodeRef factory: the Kotlin class has an internal 2-arg ctor with a
        // KClass default that Polyglot can't dispatch from a 1-arg Python
        // call. We expose the reified entry point through a single-arg path
        // (NodeRef<Node>(path)), which mirrors what scene.json coercion does
        // and matches script ergonomics.
        bindings.putMember("NodeRef", ProxyExecutable { args ->
            val path = if (args.isNotEmpty()) args[0].asString() else ""
            NodeRef<Node>(path)
        })
        bindings.putMember("Key", Key::class.java)
        bindings.putMember("BoxCollider", BoxCollider::class.java)
        bindings.putMember("Node2D", Node2D::class.java)

        val runtimeCode = PythonScriptHost::class.java.getResourceAsStream("/_nengine_runtime.py")
            ?.readBytes()?.toString(Charsets.UTF_8)
            ?: error("Missing _nengine_runtime.py classpath resource")

        context.eval(Source.newBuilder("python", runtimeCode, "_nengine_runtime.py").build())

        loadModuleFn = bindings.getMember("_nengine_load_module")
        inspectFn = bindings.getMember("_nengine_inspect")
        parseExtendsFn = bindings.getMember("_nengine_parse_extends")
        createInstanceFn = bindings.getMember("_nengine_create_instance")
    }

    override fun load(path: String, bundle: BundleSource): Script {
        val source = bundle.read(path)

        val typeName = parseExtendsFn.execute(source).let { result ->
            if (result.isNull) throw MissingExtendsDeclarationException(path)
            result.asString()
        }

        val extendsType = NodeRegistry.findBySimpleName(typeName)
            ?: throw UnknownExtendsTypeException(typeName, path)

        val exports = buildExports(source, path)

        val moduleNs = loadModuleFn.execute(source, path)
        moduleCache[path] = moduleNs

        return ScriptData(path, extendsType, exports)
    }

    private fun buildExports(source: String, path: String): List<ExportedProperty> {
        val exportsValue = inspectFn.execute(source)
        if (!exportsValue.hasArrayElements()) return emptyList()
        val result = mutableListOf<ExportedProperty>()
        for (i in 0 until exportsValue.arraySize) {
            val entry = exportsValue.getArrayElement(i)
            val name = entry.getMember("name").asString()
            val typeName = entry.getMember("type_name").asString()
            val nullable = entry.getMember("nullable").asBoolean()
            val defaultRaw = entry.getMember("default")
            val kotlinType = kotlinTypeFor(typeName)
            val default = if (defaultRaw.isNull) null else valueToKotlin(defaultRaw, kotlinType)
            result += ExportedProperty(name, kotlinType, default, nullable)
        }
        return result
    }

    private fun valueToKotlin(value: Value, type: KClass<*>): Any? {
        if (value.isNull) return null
        return when (type) {
            Float::class -> value.asDouble().toFloat()
            Int::class -> value.asInt()
            Boolean::class -> value.asBoolean()
            String::class -> value.asString()
            else -> if (value.isHostObject) value.asHostObject() else null
        }
    }

    override fun attach(node: Node, script: Script): ScriptInstance {
        val moduleNs = moduleCache[script.path]
            ?: error("Script not loaded before attach: ${script.path}")
        val instance = createInstanceFn.execute(node)
        val scriptInstance = PythonScriptInstance(instance, moduleNs)
        // Seed the instance with each export's default — callers (e.g. BundleLoader)
        // may then override individual values via setExport from scene.json `props`.
        for (export in script.exports) {
            scriptInstance.setExport(export.name, export.default)
        }
        return scriptInstance
    }

    companion object {
        fun install() {
            val context = Context.newBuilder("python")
                .allowAllAccess(true)
                .allowExperimentalOptions(true)
                .option("python.PosixModuleBackend", "java")
                // Maps Java/Kotlin bean accessors (`getX()`, `isAi()`) to Python
                // attribute access (`v.x`, `v.ai`) so script code stays
                // idiomatic instead of forcing `v.getX()` everywhere.
                .option("python.EmulateJython", "true")
                // Suppress the "fallback runtime / interpreter only" warning —
                // expected when running on a plain JDK without JVMCI. Scripts
                // here are gameplay-sized; native compilation is not the bar.
                .option("engine.WarnInterpreterOnly", "false")
                .build()
            ScriptHostRegistry.register(PythonScriptHost(context))
        }
    }
}

private data class ScriptData(
    override val path: String,
    override val extendsType: KClass<out Node>,
    override val exports: List<ExportedProperty>,
) : Script

private class PythonScriptInstance(
    private val instance: Value,
    private val moduleNs: Value,
) : ScriptInstance {

    override fun setExport(name: String, value: Any?) {
        instance.putMember(name, value)
    }

    override fun onEnter() {
        callHook("on_enter")
    }

    override fun onUpdate(dt: Float) {
        callHook("on_update", dt)
    }

    override fun onRender(renderer: Renderer) {
        callHook("on_render", renderer)
    }

    override fun onCollide(other: Node) {
        callHook("on_collide", other)
    }

    private fun callHook(name: String, vararg args: Any?) {
        if (!moduleNs.hasMember(name)) return
        val fn = moduleNs.getMember(name)
        if (fn.isNull || !fn.canExecute()) return
        fn.execute(instance, *args)
    }
}

// exception types ---------------------------------------------------------

class MissingExtendsDeclarationException(path: String) :
    RuntimeException("Script '$path' is missing an '# extends <NodeType>' declaration on its first non-empty line")

class UnknownExtendsTypeException(typeName: String, path: String) :
    RuntimeException("Script '$path' declares 'extends $typeName' but '$typeName' is not registered in NodeRegistry")

private fun kotlinTypeFor(name: String): KClass<*> = when (name) {
    "Int" -> Int::class
    "Float" -> Float::class
    "Boolean" -> Boolean::class
    "String" -> String::class
    "Vec2" -> Vec2::class
    "Color" -> Color::class
    "Rect" -> Rect::class
    "NodeRef" -> NodeRef::class
    "Key" -> Key::class
    else -> error("Unsupported export type name: $name")
}
