package com.neoutils.engine.bundle.python

import com.neoutils.engine.bundle.script.*
import com.neoutils.engine.input.Key
import com.neoutils.engine.math.Rect
import com.neoutils.engine.math.Transform
import com.neoutils.engine.math.Vec2
import com.neoutils.engine.physics.Area2D
import com.neoutils.engine.physics.CharacterBody2D
import com.neoutils.engine.physics.CircleShape2D
import com.neoutils.engine.physics.CollisionObject2D
import com.neoutils.engine.physics.CollisionShape2D
import com.neoutils.engine.physics.PhysicsBody2D
import com.neoutils.engine.physics.RectangleShape2D
import com.neoutils.engine.physics.Shape2D
import com.neoutils.engine.physics.StaticBody2D
import com.neoutils.engine.render.Color
import com.neoutils.engine.render.Renderer
import com.neoutils.engine.scene.Camera2D
import com.neoutils.engine.scene.Circle2D
import com.neoutils.engine.scene.ColorRect
import com.neoutils.engine.scene.Label
import com.neoutils.engine.scene.Line2D
import com.neoutils.engine.scene.Node
import com.neoutils.engine.scene.Node2D
import com.neoutils.engine.scene.Polygon2D
import com.neoutils.engine.serialization.NodeRef
import com.neoutils.engine.serialization.NodeRegistry
import com.neoutils.engine.serialization.Signal
import org.graalvm.polyglot.Context
import org.graalvm.polyglot.Source
import org.graalvm.polyglot.Value
import org.graalvm.polyglot.proxy.ProxyExecutable
import kotlin.reflect.KClass
import kotlin.reflect.KProperty1
import kotlin.reflect.full.memberProperties

class PythonScriptHost internal constructor(private val context: Context) : ScriptHost {

    override val extension = ".py"

    private val moduleCache = mutableMapOf<String, Value>()
    // Indexes the Python `_ScriptNode` wrapper by host Node so peer scripts
    // can reach across (e.g. PongScene wires `ball.scored.connect(...)` and
    // calls `score.increment()`). Exposed to Python via the `script_of(node)`
    // factory binding.
    private val instanceByNode = mutableMapOf<Node, Value>()

    private val loadModuleFn: Value
    private val inspectFn: Value
    private val inspectSignalsFn: Value
    private val parseExtendsFn: Value
    private val createInstanceFn: Value
    private val bareWrapperFn: Value

    init {
        val bindings = context.getBindings("python")
        // Value-type ctors are exposed as ProxyExecutable factories so script
        // code calls `Vec2(1.0, 2.0)` against a Kotlin entry point that does
        // the `double → float` cast explicitly. Binding the raw Kotlin class
        // doesn't work for Color/Rect/Vec2 because Python floats are doubles
        // and GraalPy can't always pick the right (float, float, ...) ctor
        // among the synthetic ones generated by `@Serializable` and Kotlin
        // default args (symptom: "invalid instantiation of foreign object").
        bindings.putMember("Vec2", ProxyExecutable { args ->
            Vec2(args[0].asDouble().toFloat(), args[1].asDouble().toFloat())
        })
        bindings.putMember("Color", ProxyExecutable { args ->
            val r = args[0].asDouble().toFloat()
            val g = args[1].asDouble().toFloat()
            val b = args[2].asDouble().toFloat()
            val a = if (args.size >= 4) args[3].asDouble().toFloat() else 1f
            Color(r, g, b, a)
        })
        bindings.putMember("Rect", ProxyExecutable { args ->
            Rect(args[0].asHostObject(), args[1].asHostObject())
        })
        // Transform factory: 3-arg with explicit `double → float` rotation
        // cast, plus a 1-arg shortcut for position-only updates (the most
        // common mutation pattern in scripts, replacing Kotlin's `copy(...)`).
        bindings.putMember("Transform", ProxyExecutable { args ->
            when (args.size) {
                0 -> Transform()
                1 -> Transform(position = args[0].asHostObject())
                2 -> Transform(
                    position = args[0].asHostObject(),
                    scale = args[1].asHostObject(),
                )
                3 -> Transform(
                    position = args[0].asHostObject(),
                    scale = args[1].asHostObject(),
                    rotation = args[2].asDouble().toFloat(),
                )
                else -> error("Transform takes 0..3 args (position, scale, rotation)")
            }
        })
        // NodeRef factory: the Kotlin class has an internal 2-arg ctor with a
        // KClass default that Polyglot can't dispatch from a 1-arg Python
        // call. We expose the reified entry point through a single-arg path
        // (NodeRef<Node>(path)), which mirrors what scene.json coercion does
        // and matches script ergonomics.
        bindings.putMember("NodeRef", ProxyExecutable { args ->
            val path = if (args.isNotEmpty()) args[0].asString() else ""
            NodeRef<Node>(path)
        })
        // `signal(type)` Godot-style factory. The type hint is purely
        // documentation — Python has no `Signal<T>` runtime, and the AST
        // inspector only looks for the syntactic shape `Signal = signal(...)`.
        bindings.putMember("signal", ProxyExecutable { Signal<Any?>() })
        // Lookup hook for cross-script communication: returns the Python
        // `_ScriptNode` wrapper for a host Node so the caller can invoke the
        // script's top-level def's (e.g. `score.increment()` after
        // `script_of(score_node)`). For Nodes without an attached script,
        // returns a *bare* wrapper that still exposes Kotlin-declared
        // `Signal<*>` fields via `_SignalProxy` (e.g. `Timer.timeout`); this
        // makes `script_of(some_timer).timeout.connect(handler)` work
        // uniformly across scripted and script-less Nodes. Caches the
        // bare wrapper in `instanceByNode` so repeated calls return the same
        // proxy instances (required for `.disconnect(handler)` to match).
        bindings.putMember("script_of", ProxyExecutable { args ->
            val node = args[0].asHostObject<Node>()
            instanceByNode.getOrPut(node) { bareWrapperFn.execute(node) }
        })
        // Reflection-based discovery of Kotlin `Signal<*>` `val` fields on a
        // Node. Used by `_ScriptNode` at construction time to expose every
        // Signal as a `_SignalProxy` attribute. The proxy adapts Python
        // callables to the Kotlin `Signal<T>` API and shields scripts from
        // the JVM erasure of `T` (the proxy is told whether `T == Unit` so
        // it can call zero-arg Python handlers correctly).
        bindings.putMember("_nengine_discover_signals", ProxyExecutable { args ->
            val node = args[0].asHostObject<Node>()
            discoverSignals(node)
        })
        bindings.putMember("Key", Key::class.java)
        bindings.putMember("CollisionObject2D", CollisionObject2D::class.java)
        bindings.putMember("Area2D", Area2D::class.java)
        bindings.putMember("PhysicsBody2D", PhysicsBody2D::class.java)
        bindings.putMember("StaticBody2D", StaticBody2D::class.java)
        bindings.putMember("CharacterBody2D", CharacterBody2D::class.java)
        bindings.putMember("CollisionShape2D", CollisionShape2D::class.java)
        bindings.putMember("Shape2D", Shape2D::class.java)
        bindings.putMember("RectangleShape2D", RectangleShape2D::class.java)
        bindings.putMember("CircleShape2D", CircleShape2D::class.java)
        bindings.putMember("Node2D", Node2D::class.java)
        bindings.putMember("Camera2D", Camera2D::class.java)
        bindings.putMember("ColorRect", ColorRect::class.java)
        bindings.putMember("Circle2D", Circle2D::class.java)
        bindings.putMember("Line2D", Line2D::class.java)
        bindings.putMember("Polygon2D", Polygon2D::class.java)
        bindings.putMember("Label", Label::class.java)
        bindings.putMember("Signal", Signal::class.java)

        val runtimeCode = PythonScriptHost::class.java.getResourceAsStream("/_nengine_runtime.py")
            ?.readBytes()?.toString(Charsets.UTF_8)
            ?: error("Missing _nengine_runtime.py classpath resource")

        context.eval(Source.newBuilder("python", runtimeCode, "_nengine_runtime.py").build())

        loadModuleFn = bindings.getMember("_nengine_load_module")
        inspectFn = bindings.getMember("_nengine_inspect")
        inspectSignalsFn = bindings.getMember("_nengine_inspect_signals")
        parseExtendsFn = bindings.getMember("_nengine_parse_extends")
        createInstanceFn = bindings.getMember("_nengine_create_instance")
        bareWrapperFn = bindings.getMember("_nengine_bare_wrapper")
    }

    private fun discoverSignals(node: Node): List<PySignalInfo> {
        val result = mutableListOf<PySignalInfo>()
        for (prop in node::class.memberProperties) {
            val classifier = prop.returnType.classifier as? KClass<*> ?: continue
            if (classifier != Signal::class) continue
            val arg = prop.returnType.arguments.firstOrNull()?.type
            val isUnit = (arg?.classifier as? KClass<*>) == Unit::class
            @Suppress("UNCHECKED_CAST")
            val getter = prop as KProperty1<Any, Any?>
            val sig = getter.get(node) as? Signal<Any?> ?: continue
            result += PySignalInfo(prop.name, sig, isUnit)
        }
        return result
    }

    data class PySignalInfo(val name: String, val signal: Signal<Any?>, val isUnit: Boolean)

    override fun load(path: String, bundle: BundleSource): Script {
        val source = bundle.read(path)

        val typeName = parseExtendsFn.execute(source).let { result ->
            if (result.isNull) throw MissingExtendsDeclarationException(path)
            result.asString()
        }

        val extendsType = NodeRegistry.findBySimpleName(typeName)
            ?: throw UnknownExtendsTypeException(typeName, path)

        val exports = buildExports(source, path)
        val signals = buildSignals(source, path)

        val moduleNs = loadModuleFn.execute(source, path)
        moduleCache[path] = moduleNs

        return ScriptData(path, extendsType, exports, signals)
    }

    private fun buildExports(source: String, path: String): List<ExportedProperty> {
        val exportsValue = inspectFn.execute(source)
        if (!exportsValue.hasArrayElements()) return emptyList()
        val result = mutableListOf<ExportedProperty>()
        for (i in 0 until exportsValue.arraySize) {
            val entry = exportsValue.getArrayElement(i)
            val name = entry.getMember("name").asString()
            val typeName = entry.getMember("type_name").asString()
            val nullable = entry.getMember("nullable").asBoolean()
            val defaultRaw = entry.getMember("default")
            val kotlinType = kotlinTypeFor(typeName)
            val default = if (defaultRaw.isNull) null else valueToKotlin(defaultRaw, kotlinType)
            result += ExportedProperty(name, kotlinType, default, nullable)
        }
        return result
    }

    private fun buildSignals(source: String, path: String): Map<String, SignalDeclaration> {
        val signalsValue = inspectSignalsFn.execute(source, path)
        if (!signalsValue.hasArrayElements()) return emptyMap()
        val result = linkedMapOf<String, SignalDeclaration>()
        for (i in 0 until signalsValue.arraySize) {
            val entry = signalsValue.getArrayElement(i)
            val name = entry.getMember("name").asString()
            result[name] = SignalDeclaration(name)
        }
        return result
    }

    private fun valueToKotlin(value: Value, type: KClass<*>): Any? = polyglotValueToKotlin(value, type)

    override fun attach(node: Node, script: Script): ScriptInstance {
        val moduleNs = moduleCache[script.path]
            ?: error("Script not loaded before attach: ${script.path}")
        val instance = createInstanceFn.execute(node, moduleNs)
        instanceByNode[node] = instance
        // Per-instance Signal map: each attach instantiates its own Signal
        // so two nodes sharing the same script have independent event hubs.
        // The instance is exposed back to Python via putMember; the wrapper's
        // own __dict__ shadows any module-level placeholder created by
        // `name: Signal = signal(...)` at module-load time.
        val signals = linkedMapOf<String, Signal<*>>()
        for (decl in script.signals.values) {
            val sig = Signal<Any?>()
            signals[decl.name] = sig
            instance.putMember(decl.name, sig)
        }
        val scriptInstance = PythonScriptInstance(instance, moduleNs, script, signals)
        // Seed the instance with each export's default — callers (e.g. BundleLoader)
        // may then override individual values via setExport from scene.json `properties`.
        for (export in script.exports) {
            scriptInstance.setExport(export.name, export.default)
        }
        return scriptInstance
    }

    companion object {
        /**
         * Builds a [PythonScriptHost] backed by a default GraalPy [Context].
         * Construction is expensive (it boots the GraalPy `Context` and evals
         * the runtime helpers eagerly); **reuse the returned instance across
         * multiple `BundleLoader` loads** instead of constructing one per load.
         */
        fun create(): PythonScriptHost = PythonScriptHost(defaultContext())

        private fun defaultContext(): Context = Context.newBuilder("python")
            .allowAllAccess(true)
            .allowExperimentalOptions(true)
            .option("python.PosixModuleBackend", "java")
            // Maps Java/Kotlin bean accessors (`getX()`, `isAi()`) to Python
            // attribute access (`v.x`, `v.ai`) so script code stays
            // idiomatic instead of forcing `v.getX()` everywhere.
            .option("python.EmulateJython", "true")
            // Suppress the "fallback runtime / interpreter only" warning —
            // expected when running on a plain JDK without JVMCI. Scripts
            // here are gameplay-sized; native compilation is not the bar.
            .option("engine.WarnInterpreterOnly", "false")
            .build()
    }
}

private data class ScriptData(
    override val path: String,
    override val extendsType: KClass<out Node>,
    override val exports: List<ExportedProperty>,
    override val signals: Map<String, SignalDeclaration>,
) : Script

private class PythonScriptInstance(
    private val instance: Value,
    private val moduleNs: Value,
    private val script: Script,
    override val signals: Map<String, Signal<*>>,
) : ScriptInstance {

    override fun setExport(name: String, value: Any?) {
        instance.putMember(name, value)
    }

    override fun currentValue(name: String): Any? {
        val export = script.exports.firstOrNull { it.name == name }
            ?: throw IllegalArgumentException(
                "Export '$name' is not declared in script '${script.path}'"
            )
        if (!instance.hasMember(name)) return export.default
        val raw = instance.getMember(name)
        if (raw == null || raw.isNull) return if (export.nullable) null else export.default
        return polyglotValueToKotlin(raw, export.type)
    }

    override fun onEnter() {
        callHook("_ready")
    }

    override fun onProcess(dt: Float) {
        callHook("_process", dt)
    }

    override fun onPhysicsProcess(dt: Float) {
        callHook("_physics_process", dt)
    }

    override fun onDraw(renderer: Renderer) {
        callHook("_draw", renderer)
    }

    override fun onExit() {
        callHook("_exit_tree")
    }

    override fun onAreaEntered(area: Area2D) {
        callHook("_on_area_entered", area)
    }

    override fun onAreaExited(area: Area2D) {
        callHook("_on_area_exited", area)
    }

    override fun onBodyEntered(body: PhysicsBody2D) {
        callHook("_on_body_entered", body)
    }

    override fun onBodyExited(body: PhysicsBody2D) {
        callHook("_on_body_exited", body)
    }

    private fun callHook(name: String, vararg args: Any?) {
        if (!moduleNs.hasMember(name)) return
        val fn = moduleNs.getMember(name)
        if (fn.isNull || !fn.canExecute()) return
        fn.execute(instance, *args)
    }
}

// exception types ---------------------------------------------------------

class MissingExtendsDeclarationException(path: String) :
    RuntimeException("Script '$path' is missing an '# extends <NodeType>' declaration on its first non-empty line")

class UnknownExtendsTypeException(typeName: String, path: String) :
    RuntimeException("Script '$path' declares 'extends $typeName' but '$typeName' is not registered in NodeRegistry")

class InvalidSignalDeclarationException(path: String, line: Int, name: String) :
    RuntimeException("Script '$path' line $line: '$name: Signal' must be initialized via the `signal(...)` factory")

private fun polyglotValueToKotlin(value: Value, type: KClass<*>): Any? {
    if (value.isNull) return null
    return when (type) {
        Float::class -> value.asDouble().toFloat()
        Int::class -> value.asInt()
        Boolean::class -> value.asBoolean()
        String::class -> value.asString()
        else -> if (value.isHostObject) value.asHostObject() else null
    }
}

private fun kotlinTypeFor(name: String): KClass<*> = when (name) {
    "Int" -> Int::class
    "Float" -> Float::class
    "Boolean" -> Boolean::class
    "String" -> String::class
    "Vec2" -> Vec2::class
    "Color" -> Color::class
    "Rect" -> Rect::class
    "NodeRef" -> NodeRef::class
    "Key" -> Key::class
    else -> error("Unsupported export type name: $name")
}
